// <auto-generated />
using System;
using LMUSessionTracker.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMUSessionTracker.Server.Migrations
{
    [DbContext(typeof(SqliteContext))]
    partial class SqliteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("LMUSessionTracker.Server.Models.Car", b =>
                {
                    b.Property<long>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class")
                        .HasColumnType("TEXT");

                    b.Property<long?>("EntryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SlotId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Veh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleName")
                        .HasColumnType("TEXT");

                    b.HasKey("CarId");

                    b.HasIndex("SessionId", "EntryId")
                        .IsUnique();

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("LMUSessionTracker.Server.Models.Chat", b =>
                {
                    b.Property<long>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("ChatId");

                    b.HasIndex("SessionId");

                    b.HasIndex("Timestamp", "Message")
                        .IsUnique();

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("LMUSessionTracker.Server.Models.Entry", b =>
                {
                    b.Property<long>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SlotId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Vehicle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EntryId");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("LMUSessionTracker.Server.Models.Lap", b =>
                {
                    b.Property<long>("LapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CarId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Driver")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinishStatus")
                        .HasColumnType("TEXT");

                    b.Property<double>("Fuel")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LFTire")
                        .HasColumnType("REAL");

                    b.Property<double>("LRTire")
                        .HasColumnType("REAL");

                    b.Property<int>("LapNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Pit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RFTire")
                        .HasColumnType("REAL");

                    b.Property<double>("RRTire")
                        .HasColumnType("REAL");

                    b.Property<double>("Sector1")
                        .HasColumnType("REAL");

                    b.Property<double>("Sector2")
                        .HasColumnType("REAL");

                    b.Property<double>("Sector3")
                        .HasColumnType("REAL");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalTime")
                        .HasColumnType("REAL");

                    b.Property<double>("VirtualEnergy")
                        .HasColumnType("REAL");

                    b.HasKey("LapId");

                    b.HasIndex("SessionId", "CarId");

                    b.ToTable("Laps");
                });

            modelBuilder.Entity("LMUSessionTracker.Server.Models.Member", b =>
                {
                    b.Property<long>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Badge")
                        .HasColumnType("TEXT");

                    b.Property<long>("EntryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDriver")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEngineer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MemberId");

                    b.HasIndex("SessionId", "EntryId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("LMUSessionTracker.Server.Models.Session", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<double>("EndEventTime")
                        .HasColumnType("REAL");

                    b.Property<string>("GameMode")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LapDistance")
                        .HasColumnType("REAL");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxTime")
                        .HasColumnType("REAL");

                    b.Property<uint>("MaximumLaps")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PasswordProtected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerName")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServerPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionType")
                        .HasColumnType("TEXT");

                    b.Property<double>("StartEventTime")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackName")
                        .HasColumnType("TEXT");

                    b.HasKey("SessionId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("LMUSessionTracker.Server.Models.SessionState", b =>
                {
                    b.Property<long>("SessionStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AmbientTemp")
                        .HasColumnType("REAL");

                    b.Property<double>("AveragePathWetness")
                        .HasColumnType("REAL");

                    b.Property<double>("CurrentEventTime")
                        .HasColumnType("REAL");

                    b.Property<double>("DarkCloud")
                        .HasColumnType("REAL");

                    b.Property<int?>("GamePhase")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("InRealtime")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxPathWetness")
                        .HasColumnType("REAL");

                    b.Property<double>("MinPathWetness")
                        .HasColumnType("REAL");

                    b.Property<int?>("NumRedLights")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumberOfPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumberOfVehicles")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("RaceCompletion")
                        .HasColumnType("REAL");

                    b.Property<double?>("Raining")
                        .HasColumnType("REAL");

                    b.Property<string>("Sector1Flag")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sector2Flag")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sector3Flag")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StartLightFrame")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TimeRemainingInGamePhase")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TrackTemp")
                        .HasColumnType("REAL");

                    b.Property<double?>("WindVelocity")
                        .HasColumnType("REAL");

                    b.Property<double?>("WindX")
                        .HasColumnType("REAL");

                    b.Property<double?>("WindY")
                        .HasColumnType("REAL");

                    b.Property<double?>("WindZ")
                        .HasColumnType("REAL");

                    b.Property<string>("YellowFlagState")
                        .HasColumnType("TEXT");

                    b.HasKey("SessionStateId");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("SessionStates");
                });

            modelBuilder.Entity("LMUSessionTracker.Server.Models.Car", b =>
                {
                    b.HasOne("LMUSessionTracker.Server.Models.Session", "Session")
                        .WithMany("Cars")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMUSessionTracker.Server.Models.Entry", "Entry")
                        .WithOne("Car")
                        .HasForeignKey("LMUSessionTracker.Server.Models.Car", "SessionId", "EntryId")
                        .HasPrincipalKey("LMUSessionTracker.Server.Models.Entry", "SessionId", "EntryId");

                    b.Navigation("Entry");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("LMUSessionTracker.Server.Models.Chat", b =>
                {
                    b.HasOne("LMUSessionTracker.Server.Models.Session", "Session")
                        .WithMany("Chats")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("LMUSessionTracker.Server.Models.Entry", b =>
                {
                    b.HasOne("LMUSessionTracker.Server.Models.Session", "Session")
                        .WithMany("Entries")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("LMUSessionTracker.Server.Models.Lap", b =>
                {
                    b.HasOne("LMUSessionTracker.Server.Models.Session", "Session")
                        .WithMany("Laps")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMUSessionTracker.Server.Models.Car", "Car")
                        .WithMany("Laps")
                        .HasForeignKey("SessionId", "CarId")
                        .HasPrincipalKey("SessionId", "CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("LMUSessionTracker.Server.Models.Member", b =>
                {
                    b.HasOne("LMUSessionTracker.Server.Models.Session", "Session")
                        .WithMany("Members")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMUSessionTracker.Server.Models.Entry", "Entry")
                        .WithMany("Members")
                        .HasForeignKey("SessionId", "EntryId")
                        .HasPrincipalKey("SessionId", "EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("LMUSessionTracker.Server.Models.SessionState", b =>
                {
                    b.HasOne("LMUSessionTracker.Server.Models.Session", "Session")
                        .WithOne("LastState")
                        .HasForeignKey("LMUSessionTracker.Server.Models.SessionState", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("LMUSessionTracker.Server.Models.Car", b =>
                {
                    b.Navigation("Laps");
                });

            modelBuilder.Entity("LMUSessionTracker.Server.Models.Entry", b =>
                {
                    b.Navigation("Car");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("LMUSessionTracker.Server.Models.Session", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("Chats");

                    b.Navigation("Entries");

                    b.Navigation("Laps");

                    b.Navigation("LastState");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
